name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ZurabBalamtsarashvili
        DOCKER_PASSWORD: Zurabi123!
      run: |
        docker login -u ZurabBalamtsarashvili -p Zurabi123! 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zurabbalamtsarashvili/exam:$(date +%s)
      
    - name: Docker Push
      run: docker push zurabbalamtsarashvili/exam
